CREATE TABLE SOCIO (
    IdSocio INT PRIMARY KEY AUTO_INCREMENT,
    PrimNom VARCHAR(50) NOT NULL,
    PrimApe VARCHAR(50) NOT NULL,
    FchaNac DATE NOT NULL,
    FchaIngreso DATE NOT NULL
);

CREATE TABLE USUARIO (
    IdUsuario INT PRIMARY KEY AUTO_INCREMENT,
    IdSocio INT NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Contraseña VARCHAR(255) NOT NULL,
    Rol VARCHAR(50) NOT NULL,
    FOREIGN KEY (IdSocio) REFERENCES SOCIO(IdSocio)
);

CREATE TABLE PAGO (
    IdPago INT PRIMARY KEY AUTO_INCREMENT,
    IdUsuario INT NOT NULL,
    FchaPago DATE NOT NULL,
    Monto DECIMAL(10,2) NOT NULL,
    Comprobante VARCHAR(100),
    EstadoPago VARCHAR(50) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

CREATE TABLE HORASTRABAJO (
    IdHoras INT PRIMARY KEY AUTO_INCREMENT,
    IdUsuario INT NOT NULL,
    CantHoras INT NOT NULL,
    FchaHoras DATE NOT NULL,
    EstadoHoras VARCHAR(50) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

CREATE TABLE EXONERACIONHORAS (
    IdExoneracion INT PRIMARY KEY AUTO_INCREMENT,
    IdUsuario INT NOT NULL,
    EstadoSolicitud VARCHAR(50) NOT NULL,
    FchaSolicitud DATE NOT NULL,
    Motivo TEXT,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

CREATE TABLE BAJA (
    IdBaja INT PRIMARY KEY AUTO_INCREMENT,
    IdUsuario INT NOT NULL,
    Motivo TEXT NOT NULL,
    FchaSolicitud DATE NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);

CREATE TABLE REPORTE (
    IdReporte INT PRIMARY KEY AUTO_INCREMENT,
    TipoReporte VARCHAR(100) NOT NULL,
    FchSolicitud DATE NOT NULL
);

CREATE TABLE NUCLEOFAM (
    IdNucleo INT PRIMARY KEY AUTO_INCREMENT,
    IdUsuario INT NOT NULL,
    CI VARCHAR(20) UNIQUE NOT NULL,
    FchaNac DATE NOT NULL,
    Parentesco VARCHAR(50) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES USUARIO(IdUsuario)
);
